package com.chess.mahjong.persistent.mapper;

import com.chess.mahjong.persistent.entity.NoticeTable;
import com.chess.mahjong.persistent.entity.NoticeTableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NoticeTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_table
     *
     * @mbggenerated
     */
    int countByExample(NoticeTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_table
     *
     * @mbggenerated
     */
    int deleteByExample(NoticeTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_table
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_table
     *
     * @mbggenerated
     */
    int insert(NoticeTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_table
     *
     * @mbggenerated
     */
    int insertSelective(NoticeTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_table
     *
     * @mbggenerated
     */
    List<NoticeTable> selectByExample(NoticeTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_table
     *
     * @mbggenerated
     */
    NoticeTable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_table
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") NoticeTable record, @Param("example") NoticeTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_table
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") NoticeTable record, @Param("example") NoticeTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_table
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NoticeTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_table
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NoticeTable record);

    /**
     * 获取最近的一次公告
     * @return
     */
    NoticeTable selectRecentlyObject();

}