package com.chess.mahjong.persistent.entity;

import java.util.Date;

public class Account {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.uuid
     *
     * @mbggenerated
     */
    private Integer uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.open_id
     *
     * @mbggenerated
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.nickname
     *
     * @mbggenerated
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.head_icon
     *
     * @mbggenerated
     */
    private String headIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.room_card
     *
     * @mbggenerated
     */
    private Integer roomCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.unionid
     *
     * @mbggenerated
     */
    private String unionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.province
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.sex
     *
     * @mbggenerated
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.prize_count
     *
     * @mbggenerated
     */
    private Integer prizeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.manager_up_id
     *
     * @mbggenerated
     */
    private Integer managerUpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.actual_card
     *
     * @mbggenerated
     */
    private Integer actualCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.total_card
     *
     * @mbggenerated
     */
    private Integer totalCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.last_login_time
     *
     * @mbggenerated
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.is_game
     *
     * @mbggenerated
     */
    private String isGame;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.id
     *
     * @return the value of account.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.id
     *
     * @param id the value for account.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.uuid
     *
     * @return the value of account.uuid
     *
     * @mbggenerated
     */
    public Integer getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.uuid
     *
     * @param uuid the value for account.uuid
     *
     * @mbggenerated
     */
    public void setUuid(Integer uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.open_id
     *
     * @return the value of account.open_id
     *
     * @mbggenerated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.open_id
     *
     * @param openId the value for account.open_id
     *
     * @mbggenerated
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.nickname
     *
     * @return the value of account.nickname
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.nickname
     *
     * @param nickname the value for account.nickname
     *
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.head_icon
     *
     * @return the value of account.head_icon
     *
     * @mbggenerated
     */
    public String getHeadIcon() {
        return headIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.head_icon
     *
     * @param headIcon the value for account.head_icon
     *
     * @mbggenerated
     */
    public void setHeadIcon(String headIcon) {
        this.headIcon = headIcon == null ? null : headIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.room_card
     *
     * @return the value of account.room_card
     *
     * @mbggenerated
     */
    public Integer getRoomCard() {
        return roomCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.room_card
     *
     * @param roomCard the value for account.room_card
     *
     * @mbggenerated
     */
    public void setRoomCard(Integer roomCard) {
        this.roomCard = roomCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.unionid
     *
     * @return the value of account.unionid
     *
     * @mbggenerated
     */
    public String getUnionid() {
        return unionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.unionid
     *
     * @param unionid the value for account.unionid
     *
     * @mbggenerated
     */
    public void setUnionid(String unionid) {
        this.unionid = unionid == null ? null : unionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.province
     *
     * @return the value of account.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.province
     *
     * @param province the value for account.province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.city
     *
     * @return the value of account.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.city
     *
     * @param city the value for account.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.sex
     *
     * @return the value of account.sex
     *
     * @mbggenerated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.sex
     *
     * @param sex the value for account.sex
     *
     * @mbggenerated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.prize_count
     *
     * @return the value of account.prize_count
     *
     * @mbggenerated
     */
    public Integer getPrizeCount() {
        return prizeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.prize_count
     *
     * @param prizeCount the value for account.prize_count
     *
     * @mbggenerated
     */
    public void setPrizeCount(Integer prizeCount) {
        this.prizeCount = prizeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.manager_up_id
     *
     * @return the value of account.manager_up_id
     *
     * @mbggenerated
     */
    public Integer getManagerUpId() {
        return managerUpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.manager_up_id
     *
     * @param managerUpId the value for account.manager_up_id
     *
     * @mbggenerated
     */
    public void setManagerUpId(Integer managerUpId) {
        this.managerUpId = managerUpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.actual_card
     *
     * @return the value of account.actual_card
     *
     * @mbggenerated
     */
    public Integer getActualCard() {
        return actualCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.actual_card
     *
     * @param actualCard the value for account.actual_card
     *
     * @mbggenerated
     */
    public void setActualCard(Integer actualCard) {
        this.actualCard = actualCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.total_card
     *
     * @return the value of account.total_card
     *
     * @mbggenerated
     */
    public Integer getTotalCard() {
        return totalCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.total_card
     *
     * @param totalCard the value for account.total_card
     *
     * @mbggenerated
     */
    public void setTotalCard(Integer totalCard) {
        this.totalCard = totalCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.create_time
     *
     * @return the value of account.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.create_time
     *
     * @param createTime the value for account.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.last_login_time
     *
     * @return the value of account.last_login_time
     *
     * @mbggenerated
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.last_login_time
     *
     * @param lastLoginTime the value for account.last_login_time
     *
     * @mbggenerated
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.status
     *
     * @return the value of account.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.status
     *
     * @param status the value for account.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.is_game
     *
     * @return the value of account.is_game
     *
     * @mbggenerated
     */
    public String getIsGame() {
        return isGame;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.is_game
     *
     * @param isGame the value for account.is_game
     *
     * @mbggenerated
     */
    public void setIsGame(String isGame) {
        this.isGame = isGame == null ? null : isGame.trim();
    }
}