package com.chess.mahjong.persistent.entity;

import java.util.Date;

public class RoomInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.game_type
     *
     * @mbggenerated
     */
    private String gameType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.is_hong
     *
     * @mbggenerated
     */
    private String isHong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.room_id
     *
     * @mbggenerated
     */
    private Integer roomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.seven_double
     *
     * @mbggenerated
     */
    private String sevenDouble;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.ma
     *
     * @mbggenerated
     */
    private Integer ma;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.zi_mo
     *
     * @mbggenerated
     */
    private String ziMo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.xia_yu
     *
     * @mbggenerated
     */
    private Integer xiaYu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.add_word_card
     *
     * @mbggenerated
     */
    private String addWordCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.card_numb
     *
     * @mbggenerated
     */
    private Integer cardNumb;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_info.id
     *
     * @return the value of room_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_info.id
     *
     * @param id the value for room_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_info.name
     *
     * @return the value of room_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_info.name
     *
     * @param name the value for room_info.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_info.game_type
     *
     * @return the value of room_info.game_type
     *
     * @mbggenerated
     */
    public String getGameType() {
        return gameType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_info.game_type
     *
     * @param gameType the value for room_info.game_type
     *
     * @mbggenerated
     */
    public void setGameType(String gameType) {
        this.gameType = gameType == null ? null : gameType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_info.is_hong
     *
     * @return the value of room_info.is_hong
     *
     * @mbggenerated
     */
    public String getIsHong() {
        return isHong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_info.is_hong
     *
     * @param isHong the value for room_info.is_hong
     *
     * @mbggenerated
     */
    public void setIsHong(String isHong) {
        this.isHong = isHong == null ? null : isHong.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_info.room_id
     *
     * @return the value of room_info.room_id
     *
     * @mbggenerated
     */
    public Integer getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_info.room_id
     *
     * @param roomId the value for room_info.room_id
     *
     * @mbggenerated
     */
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_info.seven_double
     *
     * @return the value of room_info.seven_double
     *
     * @mbggenerated
     */
    public String getSevenDouble() {
        return sevenDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_info.seven_double
     *
     * @param sevenDouble the value for room_info.seven_double
     *
     * @mbggenerated
     */
    public void setSevenDouble(String sevenDouble) {
        this.sevenDouble = sevenDouble == null ? null : sevenDouble.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_info.ma
     *
     * @return the value of room_info.ma
     *
     * @mbggenerated
     */
    public Integer getMa() {
        return ma;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_info.ma
     *
     * @param ma the value for room_info.ma
     *
     * @mbggenerated
     */
    public void setMa(Integer ma) {
        this.ma = ma;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_info.zi_mo
     *
     * @return the value of room_info.zi_mo
     *
     * @mbggenerated
     */
    public String getZiMo() {
        return ziMo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_info.zi_mo
     *
     * @param ziMo the value for room_info.zi_mo
     *
     * @mbggenerated
     */
    public void setZiMo(String ziMo) {
        this.ziMo = ziMo == null ? null : ziMo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_info.xia_yu
     *
     * @return the value of room_info.xia_yu
     *
     * @mbggenerated
     */
    public Integer getXiaYu() {
        return xiaYu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_info.xia_yu
     *
     * @param xiaYu the value for room_info.xia_yu
     *
     * @mbggenerated
     */
    public void setXiaYu(Integer xiaYu) {
        this.xiaYu = xiaYu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_info.add_word_card
     *
     * @return the value of room_info.add_word_card
     *
     * @mbggenerated
     */
    public String getAddWordCard() {
        return addWordCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_info.add_word_card
     *
     * @param addWordCard the value for room_info.add_word_card
     *
     * @mbggenerated
     */
    public void setAddWordCard(String addWordCard) {
        this.addWordCard = addWordCard == null ? null : addWordCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_info.create_time
     *
     * @return the value of room_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_info.create_time
     *
     * @param createTime the value for room_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_info.card_numb
     *
     * @return the value of room_info.card_numb
     *
     * @mbggenerated
     */
    public Integer getCardNumb() {
        return cardNumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_info.card_numb
     *
     * @param cardNumb the value for room_info.card_numb
     *
     * @mbggenerated
     */
    public void setCardNumb(Integer cardNumb) {
        this.cardNumb = cardNumb;
    }
}